### ISSUE TITLE
Use of module "resource" is platform-specific.

### ISSUE THREAD

**Issue by HSAR** [ficlatte/main#16]
Module "resource" is not available on Windows and blocks development on Windows machines. Error thrown from ./castle/images.py:28.

**Comment by HSAR** [comment]
Ah - thanks for sorting this out, @ethel-t-frog. I was going to fix it myself, as I'm the only one currently affected, but I hadn't come around to it.

**Comment by ethel-t-frog** [comment]
No problem.  It beats actually doing work... ;-)
