### ISSUE TITLE
Unsubscribing does not show message correctly

### ISSUE THREAD

**Issue by HSAR** [ficlatte/main#20]
The message is correct, but I rather expected it to be within the green highlight area. See below.

![image](https://cloud.githubusercontent.com/assets/985911/22694281/77ddce2c-ed3e-11e6-8cd3-1d0cac9a76ea.png)

**Comment by stitzelj** [comment]
I'll take a look at this once I get the Challenge module finished. It's probably a simple missing div or something in the template (or the stylesheet).

**Comment by stitzelj** [comment]
This is fixed with PR #22

**Comment by ethel-t-frog** [comment]
PR 22 merged
