### ISSUE TITLE
Improved mature story block

### ISSUE THREAD

**Issue by HSAR** [ficlatte/main#21]
At the moment, "blocked" mature stories (i.e. if user preferences are turned off, or you are signed out), simply read "Story is mature". It would be nice to do something a little more complex.

(This is probably a low-priority thing, as the current implementation is completely functional)

**Comment by stitzelj** [comment]
What are you thinking in terms of 'more complex?'

**Comment by HSAR** [comment]
Reference the original Ficly implementation, which put up an informative overlay but also allowed users to click through with consent. That would be nice.

**Comment by stitzelj** [comment]
Ok, that's kinda what I thought you were thinking, but I wanted to make sure we were on the same page.

**Comment by HSAR** [comment]
There are things we could do to further that - say, drop a cookie so that a user only has to consent once in a session - but that's definitely a bit further afield.

**Comment by stitzelj** [comment]
I've been looking at this, hoping for an easy solution that also looks slicks (i.e. jQuery magic), but the way the code handles on the view, it doesn't even ship the story content to the template if the user has mature filtering enabled in their profile. Right now, the only solution I can come up with is to write an additional view that the user can call with a button in the template that basically reloads the page with the `suppression` variable set to `False`. There might yet be a better way to implement this, so I'm going to keep researching it a bit to see if there are alternatives. If you fellas come up with any golden suggestions in the meantime, I'm all ears.

**Comment by ethel-t-frog** [comment]
Given that users control whether or not they wish to see mature content, there is no fundamental reason why the server can't ship the full text regardless of the user's setting, just as long as suppressed text is not displayed until after the user decides they want to see it (as opposed to being visible for a moment then disappearing).  Sure, it will be available under "view source" on the browser, but the user can make a couple of clicks to view the text anyway.  It's not exactly secret.

**Comment by stitzelj** [comment]
Ok, then I'll have a go at changing the logic in the view for this and implementing a javascript toggle that will allow the user to choose whether they want to read the story or not. I'll probably implement it only on the story view, though, and not on all the excerpt views, as it doesn't really make sense to toggle up for just 100 characters or fewer.

**Comment by ethel-t-frog** [comment]
Sounds eminently reasonable.

**Comment by stitzelj** [comment]
This is done and included in PR #31 .
