### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by ethel-t-frog** [ficlatte/main#36]
We need to have a "credits" page, acknowledging the Open Source projects we are using, and also acknowledging the three of us and CreateSigns.com for the beautiful new logo.

The site rules page could use a work-over as well.

**Comment by stitzelj** [comment]
What kind of work-over do you have in mind for the rules page?

I'll put together a list of the projects I've borrowed code from and roll up a Credits page of some sort here at some point, as well.

**Comment by ethel-t-frog** [comment]
Not sure exactly.  I've just looked at it and it looks pretty enough.

I should probably add something like "the admins reserve the right to delete any story or comment for any reason".

And, while I'm thinking about it, a small footer like Ficly had is something that has been on my list for years.

**Comment by stitzelj** [comment]
Cool. I'll give it a once-over when I get to that point, maybe look at rules pages for similar sites for anything relevant to ours.

And I'll look back at Ficly, as well, and borrow a little inspiration from their footer.

**Comment by stitzelj** [comment]
Ok, I updated the Privacy and Rules pages, built a brand new About page the includes credits, and built a nice little footer like what you've been dreaming about. :) I've got all that up in a branch on my repo. You're welcome to browse over the copy and suggest changes if you'd like or wait to deal with that until I formalize it with a pull request.

**Comment by ethel-t-frog** [comment]
Jim sorted it.  Thanks Jim.
