### ISSUE TITLE
Links on the author profile page have the ficlatte URL incorrectly pre-pended.

### ISSUE THREAD

**Issue by HSAR** [ficlatte/main#39]
Repro:
Go to to your profile
Set the "Site URL"
View your profile

Expected: Link should reflect the "Site URL" field
Actual: Link reads `https://ficlatte.com/authors/[your author ID]/[your site URL]`, which leads to a 404 page when visited.

**Comment by HSAR** [comment]
Secondary issue - the "Site Name" field seems to be completely disregarded at this time.

**Comment by stitzelj** [comment]
It's weird. Any URL you enter into the Site URL field has to have 'http://' prepended to it in order for it to display properly. I'm not sure why the the Ficlatte author URL gets prepended in any other case. There's nothing I can find in the code that would cause that, but I'll keep looking over it and see if I can figure it out.

As to the Site Name field, I changed the alt parameter in the anchor link to title, so the site name will display on mouseover.

**Comment by stitzelj** [comment]
Oh, I figured it out. The site URL parameter is inside an anchor link, so if you don't include the 'http://' in the field, it's going to treat it as a relative link to the current page.

**Comment by stitzelj** [comment]
I also updated the Placeholder text for the Site URL field to display 'http://example.com' to demonstrate what format site links should take for that field.
