### ISSUE TITLE
Password-lost UI

### ISSUE THREAD

**Issue by ethel-t-frog** [ficlatte/main#6]
Need a way to send a reset-my-password e-mail to the registered e-mail address of a user.

**Comment by HSAR** [comment]
We don't have this? I wonder if we've had any users lost.

**Comment by stitzelj** [comment]
This issue is in development. I should have a commit ready for review and deployment today or tomorrow.

**Comment by stitzelj** [comment]
This feature has been included in the current pull request.

**Comment by stitzelj** [comment]
This is resolved with #15, so this issue can be closed.
